# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ename', models.CharField(db_column='eng_name', max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('comeout', models.DateField(db_column='come_out')),
                ('country', models.CharField(max_length=20)),
                ('intro', models.TextField(max_length=500)),
                ('url', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket_movie',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ticket_order',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='start_time')),
                ('price', models.FloatField()),
                ('seat', models.CharField(max_length=60)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='seat.Movie')),
            ],
            options={
                'db_table': 'ticket_session',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('nickname', models.CharField(max_length=64)),
                ('head', models.CharField(max_length=200)),
                ('remaining', models.FloatField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='seat.Session'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='seat.User'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('session_id', 'user_id')]),
        ),
    ]
