# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(db_column='movieID', primary_key=True, serialize=False)),
                ('imageurl', models.CharField(blank=True, db_column='imageURL', max_length=100, null=True)),
                ('moviename', models.CharField(blank=True, db_column='movieName', max_length=100, null=True)),
                ('totaltime', models.DateTimeField(blank=True, db_column='totalTime', null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('derictor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='sessionID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('seat', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(db_column='ticketID', primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='userID', max_length=100, null=True)),
                ('seatid', models.CharField(blank=True, db_column='seatID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
